#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        child_frame_id: lidar
        parent_frame_id: world
     
optitrack_config:
        multicast_address: 224.0.0.1
