laser_topic: "velodyne_points"
output_topic: "sync_data_out"
cam_1_id: "30400333"
cam_2_id: "30400337"
output_topic_lidar: "output_lidar"
output_topic_img_1: "output_img_1"
output_topic_img_2: "output_img_2"
